> ### **Assignment 2 - Numpy Array Operations** 


# My top 5 Numpy functions for a next level python coding project


### All about my functions

These 5 functions are a brief search of mine, on the most useful functions to make useful calculations or other analysis . As an electrical engineering student I found the use of these functions quite necessary.
- numpy.binary_repr
- numpy.linalg.solve
- numpy.mean
- numpy.roots
- numpy.fft.fftfreq

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [46]:
!pip install jovian --upgrade -q

In [47]:
import jovian

In [48]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [49]:
import numpy as np

In [50]:
# List of functions explained 
function1 = np.binary_repr 
function2 = np.linalg.solve
function3 = np.mean
function4 = np.roots
function5 = np.fft.fftfreq

   ## Function 1 - np.binary_repr
Outputs the binary representation of a number  as a string,  a width argument can also be passed to output a string with a length equal to the width argument 

In [51]:
# Example 1 - working (change this)

np.binary_repr(8)

'1000'

The binary representation of a number without a given width as a string

In [52]:
# Example 2 - working

np.binary_repr(-9)

'-1001'

The binary representation of a negative number, this numpy function returns the number in binary with a minus sign 
added to the front if width is not given, if width is given,the two’s complement of the number is returned, with respect to that width.

In [53]:
# Example 3 - breaking (to illustrate when it breaks)

np.binary_repr(6.7)

TypeError: 'float' object cannot be interpreted as an integer

This function returns error when a float number is passed as its argument, float objects cannot be interpreted as an integer using this function, if one would want to have the binary representation of a float number this function would not be used

This function can be used to numerous applications , for basically every digital converter we want in a digital communications system for example or wherever a digital representation of a number is required to build a digital system and to almost infinite other applications.

In [54]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Function 2 - np.linalg.solve

Solves the  linear matrix equation, ax=b given matrices a and b

In [55]:
# Example 1 - working
a = np.array([[4,5], [2,3]])
b=np.array([7,9])
x=np.linalg.solve(a,b)
x

array([-12.,  11.])

Solve a linear matrix equation, ax=b

In [56]:
# Example 2 - working
a = np.array([[2.1,5.2], [2.3,3.8]])
b=np.array([7.5,9.6])
x=np.linalg.solve(a,b)
x

array([ 5.38190955, -0.73115578])

Same as before only that now float values everywhere appear, does not break the function though

In [57]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[2.1,5.2], [2.3,3.8]])
b=np.array([7.5,9.6,9])
x=np.linalg.solve(a,b)
x

ValueError: solve1: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (m,m),(m)->(m) (size 3 is different from 2)

This example breaks the function use because of the b array, this time our b array is a 3x1 array and size 3 is different than size 2 of a's dimensions, therefore this linear equation is impossible to be solved. , b's dimension of rows must be equal to the a's dimension in order for this linear equation ot be solved, array a must also be square too.

One can use this function to solve when he or she wants to solve a system with linear scalar equations . Very useful for numerous calculations

In [58]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Function 3 - np.mean

Compute the arithmetic mean along the specified axis. (axis=0 means along the vertical axis y and axis=1 means along the horizontal axis x).

In [59]:
# Example 1 - working
np.array([[1,7],
   [3,8],
   [8,9]
  ])
np.mean(a)

3.3500000000000005

 If no axis input is given computes the total mean of the flattened array.

In [60]:
# Example 2 - working
a = np.ones((2,512*512),dtype=np.float32)
a[0,:]=0.4
a[1,:]=0.6
np.mean(a,dtype=np.float64)


0.5000000149011612

Here we create a 2x262,144 matrix which we then fill  with float values in each line and then compute the mean value of the flattened array, if we specify a bigger datatype we can have better accuracy of the mean value.

In [61]:
# Example 3 - breaking (to illustrate when it breaks)
a = [5,3,3.45,7]

np.mean(a,dtype=np.float64)

4.6125

The mean function cannot compute the mean value of an array that contains multiple types of values. This is obvious , although it can compute for float and int values in one array, strings and booleans are not converted into a value or something for the function to compute.

This function is used many times in data analysis to have the average value of a quantity or a dataset to proceed in data processing, data visualization and many many more applications.From basic computations to complex visualizations

In [62]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Function 3 - np.mean
Compute the arithmetic mean along the specified axis. (axis=0 means along the vertical axis y and axis=1 means along the horizontal axis x).


In [63]:
# Example 1 - working
a=np.array([[1,7],
   [3,8],
   [8,9]
  ])
np.mean(a)

6.0

 If no axis input is given computes the total mean of the flattened array.

In [64]:
# Example 2 - working
a = np.ones((2,512*512),dtype=np.float32)
a[0,:]=0.4
a[1,:]=0.6
np.mean(a,dtype=np.float64)

0.5000000149011612

Here we create a 2x262,144 matrix which we then fill  with float values in each line and then compute the mean value of the flattened array, if we specify a bigger datatype we can have better accuracy of the mean value.

In [65]:
# Example 3 - breaking (to illustrate when it breaks)
a = [5,'word',6.7,True]

np.mean(a,dtype=np.float64)

TypeError: cannot perform reduce with flexible type

The mean function cannot compute the mean value of an array that contains multiple types of values. This is obvious , although it can compute for float and int values in one array, strings and booleans are not converted into a value or something for the function to compute.




This function is used many times in data analysis to have the average value of a quantity or a dataset to proceed in data processing, data visualization and many many more applications.From basic computations to complex visualizations


In [66]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Function 4-np.roots

This function returns the roots of a polynomial equation with coefficients equal to the elements of the given array.If the length of the array is n+1 , then the polynomial is described by: 
p[0] * x^n + p[1] * x^(n-1) + ... + p[n-1]*x + p[n]

In [67]:
# Example 1 - working
np.roots([1,4,7,5])

array([-1.21507985+1.30714128j, -1.21507985-1.30714128j,
       -1.56984029+0.j        ])

Simple polynomial roots calculation, the output array has all the roots of the equation

In [68]:
# Example 2 - working
np.roots([-4,5.46,45])

array([ 4.105336, -2.740336])

Coefficients ( input array elements) can also be negative or float values as well.

In [69]:
# Example 3 - breaking (to illustrate when it breaks)
np.roots([True,'word',5])

ValueError: could not convert string to float: 'True'

There cannot be multiple types of values in our input array , or else the funtion breaks since there cannot be string type values or booleans for coefficients of a polynomial equation

This function is used whenever we need to compute the roots of a polynomial equation, so basically everywhere . Engineering , maths, physics even chemistry and finances . Numerous applications and uses.

In [70]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Function 5 - np.fft.fftfreq

Return the Discrete Fourier Transform sample frequencies.

The returned float array f contains the frequency bin centers in cycles per unit of the sample spacing (with zero at the start). For instance, if the sample spacing is in seconds, then the frequency unit is cycles/second.

In [71]:
# Example 1 - working
signal = np.array([-2, 8, 6, 4, 1, 0, 3, 5], dtype=float)
n = signal.size
np.fft.fftfreq(n)


array([ 0.   ,  0.125,  0.25 ,  0.375, -0.5  , -0.375, -0.25 , -0.125])

The output array contains all the fourier transform sample frequencies with a deafualt spacing equal to 1 

In [74]:
# Example 2 - working
signal = np.array([-2, 8, 6, 4, 1, 0, 3, 5], dtype=float)
n = signal.size
timestep=0.1
np.fft.fftfreq(n,d=timestep)


array([ 0.  ,  1.25,  2.5 ,  3.75, -5.  , -3.75, -2.5 , -1.25])

Timestep is passed as an argument for a different sample spacing 

In [75]:
# Example 3 - breaking (to illustrate when it breaks)
signal = np.array([-2, 8, 'word', True, 1, 0, 3, 5], dtype=float)
n = signal.size
timestep=0.1
np.fft.fftfreq(n,d=timestep)


ValueError: could not convert string to float: 'word'

Cannot compute the fourier transform sampling frequencies for a signal that contains a string value or a bollena value because that is not part of a real signal. Never!

Fourier analysis is fundamentally a method for expressing a function as a sum of periodic components, and for recovering the function from those components. 
Because the discrete Fourier transform separates its input into components that contribute at discrete frequencies, it has a great number of applications in digital signal processing.

In [76]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ladiasnk-eca/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/ladiasnk-eca/numpy-array-operations


'https://jovian.ai/ladiasnk-eca/numpy-array-operations'

## Conclusion
In this notebbok I covered my 5 personal favourite numpy functions and discussed some things about them after presenting some examples for each one.

## Reference Links
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/doc/stable/reference/routines.html

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
